
tissueKey <- list(adipose_tissue = "adipose_tissue",
                  adrenal_gland= "adrenal_gland",
                  bone_marrow = c("bone_marrow"),
                  brain = c("basal_ganglia","amygdala",
                     "cerebellum", "cerebral_cortex", "white_matter",
                     "hypothalamus", "hippocampal_formation",
                     "medulla_oblongata", "midbrain", "thalamus",
                     "pons", "spinal_cord"),
                  breast = "breast",
                  cervix = "cervix",
                  choroid_plexus = "choroid_plexus",
                  endometrium = "endometrium",
                  epididymis = "epididymis",
                  esophagus = "esophagus",
                  fallopian_tube = "fallopian_tube",
                  gallbladder = "gallbladder",
                  heart_muscle = "heart_muscle",
                  intestine = c("colon", "duodenum", "rectum", "small_intestine"),
                  kidney = "kidney",
                  liver = "liver",
                  lymphoid_tissue = c("lymph_node","spleen", 
                                      "appendix", "tonsil", "thymus"),
                  lung = "lung",
                  pancreas = "pancreas",
                  parathyroid_gland = "parathyroid_gland",
                  pituitary_gland = "pituitary_gland",
                  placenta = "placenta",
                  prostate = "prostate",
                  retina = "retina",
                  salivary_gland = "salivary_gland",
                  seminal_vesicle = "seminal_vesicle",
                  skeletal_muscle = "skeletal_muscle",
                  skin = "skin",
                  smooth_muscle = "smooth_muscle",
                  stomach = "stomach",
                  testis = "testis",
                  thyroid_gland = "thyroid_gland",
                  tongue = "tongue",
                  urinary_bladder = "urinary_bladder",
                  vagina = "vagina",
                  ovary = "ovary"
)  
                  

#unique(hpacon$Tissue )[!unique(hpacon$Tissue ) %in% unlist(tissueKey) ]
#unique(unlist(secTissues))[!unique(unlist(secTissues)) %in% names(tissueKey)]
